services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: keycloak
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    depends_on:
      - postgres
    command: 
      - start-dev 
      - --import-realm
    ports:
      - "8080:8080"
    restart: always
    environment:
      # Database
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${DB_USER}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      
      # Admin
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      
      # Hostname Config für Email Links
      KC_HTTP_RELATIVE_PATH: /keycloak
      KC_HOSTNAME: xn--ther-uoa.tech
      KC_PROXY: edge
      
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/exports:/opt/keycloak/data/import
  backend:
    image: ${DOCKER_USERNAME}/aether-backend:latest
    container_name: backend
    restart: on-failure
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/aether
      SWAGGER_TOKEN_URL: https://xn--ther-uoa.tech/keycloak/realms/HotTopics/protocol/openid-connect/token
      KEYCLOAK_BASE_URL: https://xn--ther-uoa.tech/keycloak
      KEYCLOAK_URL: https://xn--ther-uoa.tech/keycloak/realms/HotTopics
      KEYCLOAK_INTERNAL_URL: https://xn--ther-uoa.tech/keycloak/realms/HotTopics
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_HOSTNAME: keycloak
      KEYCLOAK_ADMIN_CLIENT_ID: backend-admin-client
      KEYCLOAK_ADMIN_CLIENT_SECRET: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
      KEYCLOAK_CLIENT_ID: HotTopics
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: telegramdb
      POSTGRES_USER: telegramuser
      NEO4J_USER: neo4j
      NEO4J_URI: bolt://neo4j:7687
      JOB_LAUNCHER_URL: http://job-launcher:9001
      TG_API_ID: ${TG_API_ID}
      TG_API_HASH: ${TG_API_HASH}
      TG_PHONE: ${TG_PHONE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      JOB_SECRET_TOKEN: ${JOB_SECRET_TOKEN}
      MEDIA_PATH: ${PWD}/shared/media
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tg_sessions:/app/sessions
      - ${PWD}/shared/media:/shared/media
    depends_on:
      - postgres
      - keycloak
    ports:
      - "8000:8000"
  frontend:
    image: ${DOCKER_USERNAME}/aether-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      PROD_DOMAIN: ${PROD_DOMAIN}
    volumes:
      - ./frontend:/app
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./shared/media:/usr/share/nginx/html/app/public/media
    restart: always
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'sleep 10 && certbot certonly --webroot -w /var/www/certbot -d ${PROD_DOMAIN} --email ${PROD_MAIL} --agree-tos --non-interactive'"

  neo4j:
    image: neo4j:5.18
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP browser (optional)
      - "7687:7687"   # Bolt (for drivers like your scraper)
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_PLUGINS: '["apoc","graph-data-science"]'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "${NEO4J_USER}", "-p", "${NEO4J_PASSWORD}", "RETURN 1"]
      interval: 10s
      retries: 10
    
  telegram-job:
    image: ${DOCKER_USERNAME}/aether-telegram_scraper:latest
    container_name: telegram_scraper
    #entrypoint: ["sleep", "infinity"]  # Keeps image warm but does nothing unless called
    volumes:
      - tg_sessions:/app/sessions    # ⬅️ Session volume (Telegram auth)
      - ./shared/media:/shared/media
    # profiles: ["scraper"] 
  job-launcher:
    image: ${DOCKER_USERNAME}/aether-job_launcher:latest
    container_name: job_launcher
    ports:
      - "9001:9001"
    environment:
      JOB_SECRET_TOKEN: ${JOB_SECRET_TOKEN}
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      TG_API_ID: ${TG_API_ID}
      TG_API_HASH: ${TG_API_HASH}
      MEDIA_PATH: ${PWD}/shared/media
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tg_sessions:/app/sessions
volumes:
  pgdata:
  neo4j_data:
  neo4j_logs:
  keycloak_data:
  tg_sessions: